modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="gtceu"
type="required"
versionRange="[7.0.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="required"
versionRange="[${ae2_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="extendedae"
type="required"
versionRange="[${extendedae_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="advanced_ae"
type="required"
versionRange="[${advancedae_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="justdirethings"
type="required"
versionRange="[${jdt_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[${jei_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
type="optional"
versionRange="[${emi_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[${jade_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="occultism"
type="required"
versionRange="[${occultism_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ponder"
type="required"
versionRange="[${ponder_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ftbteams"
type="optional"
versionRange="[${ftbteams_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs"
type="optional"
versionRange="[${kubejs_version},)"
ordering="AFTER"
side="BOTH"
